#!/usr/bin/env python3
"""Email a DTL PDF report to a recipient via Gmail SMTP.

Reads the Gmail app password from (in order):
  1. env var GMAIL_APP_PASSWORD
  2. macOS keychain: service "dtl-gmail-app-password", account boravelli.sreeharsha@gmail.com

If neither is set, prints exact setup instructions and exits 1.

Usage:
  python3 dtl_send_email.py <pdf_path> <subject> [recipient]

Defaults:
  recipient = boravelli.sreeharsha@gmail.com
"""
import os
import sys
import smtplib
import subprocess
from email.message import EmailMessage
from pathlib import Path

SENDER = "boravelli.sreeharsha@gmail.com"
DEFAULT_RECIPIENT = "boravelli.sreeharsha@gmail.com"
KEYCHAIN_SERVICE = "dtl-gmail-app-password"


def get_app_password() -> str | None:
    pw = os.environ.get("GMAIL_APP_PASSWORD")
    if pw:
        return pw.strip()
    try:
        out = subprocess.run(
            ["security", "find-generic-password", "-s", KEYCHAIN_SERVICE, "-a", SENDER, "-w"],
            capture_output=True, text=True, timeout=5,
        )
        if out.returncode == 0 and out.stdout.strip():
            return out.stdout.strip()
    except Exception:
        pass
    return None


def setup_instructions() -> str:
    return (
        "Gmail SMTP credential not found.\n\n"
        "One-time setup:\n"
        "  1. Create an app password at https://myaccount.google.com/apppasswords\n"
        "     (requires 2FA on the Gmail account).\n"
        "  2. Store it in the macOS keychain:\n"
        f"       security add-generic-password -s {KEYCHAIN_SERVICE} \\\n"
        f"         -a {SENDER} -w 'YOUR_16_CHAR_APP_PASSWORD'\n"
        "     (or export GMAIL_APP_PASSWORD=... for one-off testing).\n"
    )


def main() -> int:
    if len(sys.argv) < 3:
        print("Usage: dtl_send_email.py <pdf_path> <subject> [recipient]", file=sys.stderr)
        return 2

    pdf_path = Path(sys.argv[1]).expanduser().resolve()
    subject = sys.argv[2]
    recipient = sys.argv[3] if len(sys.argv) > 3 else DEFAULT_RECIPIENT

    if not pdf_path.is_file():
        print(f"PDF not found: {pdf_path}", file=sys.stderr)
        return 1

    pw = get_app_password()
    if not pw:
        print(setup_instructions(), file=sys.stderr)
        return 1

    msg = EmailMessage()
    msg["From"] = SENDER
    msg["To"] = recipient
    msg["Subject"] = subject
    msg.set_content(
        f"DTL report attached: {pdf_path.name}\n\n"
        "Generated by /dtl on TradingView MCP.\n"
    )
    data = pdf_path.read_bytes()
    msg.add_attachment(data, maintype="application", subtype="pdf", filename=pdf_path.name)

    try:
        with smtplib.SMTP("smtp.gmail.com", 587, timeout=30) as s:
            s.starttls()
            s.login(SENDER, pw)
            s.send_message(msg)
    except smtplib.SMTPAuthenticationError as e:
        print(f"SMTP auth failed: {e}\n\n{setup_instructions()}", file=sys.stderr)
        return 1
    except Exception as e:
        print(f"Send failed: {e}", file=sys.stderr)
        return 1

    print(f"Sent {pdf_path.name} ({len(data):,} bytes) to {recipient}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
